# Inserts a blank line between shell prompts
add_newline = true

[line_break]
disabled = false

[directory]
truncation_length = 0
truncate_to_repo = true
style = "cyan"

[golang]
disabled = true

[memory_usage]
disabled = false
threshold = 75

[docker_context]
disabled = false

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[🍒 PICKING](bold red)"
disabled = false

[git_status]
disabled = false
up_to_date = "[✓](green)"
conflicted = "CONFLICTED "
ahead = "[AHEAD](yellow)"
behind = "BEHIND"
diverged = "DIVERGED"
untracked = "UNTRACKED"
stashed = "[STASHED](yellow)"
modified = "MODIFIED"
renamed = "RENAMED"
deleted = "DELETED"
staged = '[++\($count\)](yellow)'

[git_metrics]
added_style = "bold blue"
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '
disabled = true

[time]
disabled = true
time_format = "%T"
utc_time_offset = "-5"

[gcloud]
disabled = true

[aws]
disabled = true
force_display = true

[kubernetes]
format = ' [$context](bold red)([$namespace](red)) '
disabled = false
[kubernetes.context_aliases]
"arn:aws:eks:us-east-1:710015040892:cluster/stage-320d9422df2c52a0f810" = "stage-context"
"arn:aws:eks:us-east-1:710015040892:cluster/prod-c421d55861f633ac5346" = "prod-context"
[kubernetes.user_aliases]
"arn:aws:eks:us-east-1:710015040892:cluster/stage-320d9422df2c52a0f810" = "user-stage"
"arn:aws:eks:us-east-1:710015040892:cluster/prod-c421d55861f633ac5346" = "user-prod"
